

services:
  chatbot_rag:
    build: .
    container_name: chatbot_rag
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app/chatbot_rag  
    command: uvicorn chatbot_rag.app.main:app --host 0.0.0.0 --port 8000 --reload
